# Generated by Django 4.1.1 on 2022-09-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Move',
            new_name='Movie',
        ),
    ]
